# GitLab
server {
    listen 80;
    server_name edukacjawisniowa.pl;

    location / {
        proxy_pass http://gitlab:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# student1
server {
    listen 80;
    server_name student1.edukacjawisniowa.pl;

    location / {
        proxy_pass http://student1:80;
        proxy_set_header Host $host;
    }
}

#student2
server {
    listen 80;
    server_name student2.edukacjawisniowa.pl;

    location / {
        proxy_pass http://student2:80;
        proxy_set_header Host $host;
    }
}
